#!/bin/sh -e

pkg=r-cran-backports
if [ "$AUTOPKGTEST_TMP" = "" ] ; then
  AUTOPKGTEST_TMP=`mktemp -d /tmp/${pkg}-test.XXXXXX`
  trap "rm -rf $AUTOPKGTEST_TMP" 0 INT QUIT ABRT PIPE TERM
fi
cd $AUTOPKGTEST_TMP
cp -a /usr/share/doc/${pkg}/tests/* $AUTOPKGTEST_TMP
# gunzip *.gz
export LC_ALL=C
for test in *R
do
  echo "Testing ${test}"
  R CMD BATCH ${test}
  if [ ! $? ] ; then
    echo "Test ${test} failed"
    exit 1
  else
    echo "Test ${test} passed"
  fi
  rm -f ${test}out .RData
done
